cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: 버킷 이름
      dir: S3 디렉토리 이름
    region:
      static: ap-northeast-2
    stack:
      auto: false